server.port=8081

# H2 Database (for deployment)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
jwt.secret=55d2146ff74fb8a87a6c0c2a23e59f4931a2386928e46950293b21ad9ec50302
jwt.expirationMs=86400000

spring.sql.init.mode=always
spring.main.allow-circular-references=true